create sequence answer_seq start 1 increment 1;
create sequence competition_seq start 1 increment 1;
create sequence option_seq start 1 increment 1;
create sequence participant_answer_seq start 1 increment 1;
create sequence participant_seq start 1 increment 1;
create sequence role_seq start 1 increment 1;
create sequence source_code_seq start 1 increment 1;
create sequence subject_seq start 1 increment 1;
create sequence task_seq start 1 increment 1;
create sequence test_seq start 1 increment 1;
create sequence user_seq start 1 increment 1;
create table answer (id int8 not null, answer varchar(255), task_id int8, primary key (id)) ;
create table competition (id int8 not null, end_datetime timestamp, name varchar(50) not null, start_datetime timestamp, subject_id int8, user_id int8, primary key (id));
create table option (id int8 not null, is_correct boolean default false, option varchar(255), task_id int8, primary key (id));
create table participant (id int8 not null, end_datetime timestamp, score float4, start_datetime timestamp, competition_id int8, user_id int8, primary key (id));
create table participant_answer (id int8 not null, is_correct boolean default false, option varchar(255), participant_id int8, task_id int8, primary key (id));
create table role (id int8 not null, name varchar(50) not null, primary key (id));
create table source_code (id int8 not null, memory_limit float4, time_limit float4, task_id int8, primary key (id));
create table subject (id int8 not null, name varchar(50) not null, primary key (id));
create table "task" (id int8 not null, description varchar(255), task_type varchar(255), competition_id int8, primary key (id));
create table test (id int8 not null, input varchar(255), output varchar(255), source_code_id int8, primary key (id));
create table users (id int8 not null, create_date timestamp, login varchar(255) not null, name varchar(255) not null, password varchar(255) not null, patronymic varchar(255), surname varchar(255), primary key (id));
create table users_roles (users_id int8 not null, roles_id int8 not null, primary key (users_id, roles_id));
alter table answer add constraint UKgekuxbdwejftco8f0a1adqw39 unique (task_id);
alter table source_code add constraint UK78h9jq6b7d9g4gi5sc71acwmx unique (task_id);
alter table users add constraint UK_ow0gan20590jrb00upg3va2fn unique (login);
alter table participant add constraint UK_67f133k3yik28o7lnlsqry5fe unique (user_id);
alter table answer add constraint FK8yia55x5xhg4o5a8jxdj9ws8b foreign key (task_id) references "task" ON DELETE CASCADE;
alter table competition add constraint FKbc1e987p5l810g8b4bj4hy5xv foreign key (subject_id) references subject;
alter table competition add constraint FKgyr4whp7gj44n27eb4irravua foreign key (user_id) references users;
alter table option add constraint FKggf14hq10t57h2ht50aidubny foreign key (task_id) references "task" ON DELETE CASCADE;
alter table participant add constraint FKqpiwun2nlyenl4ptfu5j3h9lj foreign key (competition_id) references competition;
alter table participant add constraint FK5mkbmcdbhnooj3v3ubcnreah9 foreign key (user_id) references users;
alter table participant_answer add constraint FKha22j4447ot7etlcjek1l4j1y foreign key (participant_id) references participant;
alter table participant_answer add constraint FKpt8523211ouae40hy7yk79le5 foreign key (task_id) references "task";
alter table source_code add constraint FKcvjwi76f9bojhne7l4epp0a1x foreign key (task_id) references "task" ON DELETE CASCADE;
alter table "task" add constraint FKfp0l0y4gf60v88krmvhij5pfr foreign key (competition_id) references competition;
alter table test add constraint FK15q7e6m34oweb54my8yboe9hf foreign key (source_code_id) references source_code ON DELETE CASCADE;
alter table users_roles add constraint FK15d410tj6juko0sq9k4km60xq foreign key (roles_id) references role;
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users;